public enum Opzioni {
    ACCESO,
    GIA_ACCESO,
    SPENTO,
    GIA_SPENTO,
    SPORTELLO_APERTO,
    SPORTELLO_GIA_APERTO,
    LAVAGGIO_IN_CORSO,
    SPORTELLO_CHIUSO,
    SPORTELLO_GIA_CHIUSO,
    DETERSIVO_AGGIUNTO,
    DETERSIVO_GIA_AGGIUNTO,
    TEMPERATURA_IMPOSTATA,
    TEMPERATURA_NON_VALIDA,
    TEMPERATURA_NON_IMPOSTABILE,
    LAVAGGIO_AVVIATO,
    SPORTELLO_LAVAGGIO,
    DETERSIVO_LAVAGGIO,
    ACCESO_LAVAGGIO,
    LAVAGGIO_TERMINATO,
    LAVAGGIO_GIA_TERMINATO

}
